### ISSUE TITLE
Message "failed to highlight code" in every step after @enter

### ISSUE THREAD

**Issue by adediego** [JuliaDebug/Debugger.jl#303]
I get this message when using ```@enter``` in a fresh julia environment (Debugger v0.7.0, Julia 1.7.1 on Fedora 35):
```
julia> using Debugger
julia> @enter sin(1)
failed to highlight code, TypeError(Symbol("keyword argument"), :bold, Union{Nothing, Bool}, :nothing)
failed to highlight code, TypeError(Symbol("keyword argument"), :bold, Union{Nothing, Bool}, :nothing)
In sin(x) at math.jl:1218
 1218  @eval function ($f)(x::Real)
>1219      xf = float(x)
 1220      x === xf && throw(MethodError($f, (x,)))
 1221      return ($f)(xf)
 1222  end

About to run: (float)(1)
1|debug> 
```
The message disappeared when I changed all appearances of ```:nothing``` to ```nothing``` in ```Format.render``` at line 201 of printing.jl, but I only had a very superficial look on the code so I'm not sure if that would be the right fix.

**Comment by simeonschaub** [comment]
> The message disappeared when I changed all appearances of :nothing to nothing in Format.render at line 201 of printing.jl, but I only had a very superficial look on the code so I'm not sure if that would be the right fix.

Yes, do you want to make a PR? Alongside, the compat bound for Crayons.jl should also be changed to require Crayons 4.1.

**Comment by KristofferC** [comment]
:(. That API break in Crayons was a mistake from my side..

**Comment by KristofferC** [comment]
Should be fixed by https://github.com/JuliaDebug/Debugger.jl/pull/304. Sorry for the slow response.

**Comment by adediego** [comment]
No problem, thanks for the great work!

> Alongside, the compat bound for Crayons.jl should also be changed to require Crayons 4.1.

This is still missing, right?

**Comment by KristofferC** [comment]
Yeah, let's add that too.

**Comment by reachtarunhere** [comment]
I am still facing this issue with the latest version? Is it assumed to be fixed?
